/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author gherrada22
 * @Linkedin gherrada22
 * @Github gherrada22
 */
public class VistaCalculadoraBasica extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraBasica
     */
    public VistaCalculadoraBasica() {
        initComponents();
        this.setLocationRelativeTo(this); // Centra la ventana
        this.setTitle("Convertidor Alura Latam");
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/insigniaJava.png")).getImage()); // Añade ícono a la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonSiete = new javax.swing.JButton();
        botonClear = new javax.swing.JButton();
        botonUno = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonOcho = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonDosCeros = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonTres = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonPor = new javax.swing.JButton();
        botonEntre = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        textPantallaCalculadora = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 29, 59));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculadora");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calculadora básica para realizar cálculos simples con dos valores.");

        botonSiete.setBackground(new java.awt.Color(255, 255, 255));
        botonSiete.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonSiete.setForeground(new java.awt.Color(5, 29, 59));
        botonSiete.setText("7");
        botonSiete.setBorder(null);
        botonSiete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSiete.setFocusPainted(false);

        botonClear.setBackground(new java.awt.Color(255, 255, 255));
        botonClear.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonClear.setForeground(new java.awt.Color(5, 29, 59));
        botonClear.setText("C");
        botonClear.setBorder(null);
        botonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonClear.setFocusPainted(false);

        botonUno.setBackground(new java.awt.Color(255, 255, 255));
        botonUno.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonUno.setForeground(new java.awt.Color(5, 29, 59));
        botonUno.setText("1");
        botonUno.setBorder(null);
        botonUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonUno.setFocusPainted(false);

        botonCero.setBackground(new java.awt.Color(255, 255, 255));
        botonCero.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonCero.setForeground(new java.awt.Color(5, 29, 59));
        botonCero.setText("0");
        botonCero.setBorder(null);
        botonCero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCero.setFocusPainted(false);

        botonCuatro.setBackground(new java.awt.Color(255, 255, 255));
        botonCuatro.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonCuatro.setForeground(new java.awt.Color(5, 29, 59));
        botonCuatro.setText("4");
        botonCuatro.setBorder(null);
        botonCuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCuatro.setFocusPainted(false);

        botonOcho.setBackground(new java.awt.Color(255, 255, 255));
        botonOcho.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonOcho.setForeground(new java.awt.Color(5, 29, 59));
        botonOcho.setText("8");
        botonOcho.setBorder(null);
        botonOcho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonOcho.setFocusPainted(false);

        botonDos.setBackground(new java.awt.Color(255, 255, 255));
        botonDos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonDos.setForeground(new java.awt.Color(5, 29, 59));
        botonDos.setText("2");
        botonDos.setBorder(null);
        botonDos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDos.setFocusPainted(false);

        botonDosCeros.setBackground(new java.awt.Color(255, 255, 255));
        botonDosCeros.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonDosCeros.setForeground(new java.awt.Color(5, 29, 59));
        botonDosCeros.setText("00");
        botonDosCeros.setBorder(null);
        botonDosCeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDosCeros.setFocusPainted(false);

        botonCinco.setBackground(new java.awt.Color(255, 255, 255));
        botonCinco.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonCinco.setForeground(new java.awt.Color(5, 29, 59));
        botonCinco.setText("5");
        botonCinco.setBorder(null);
        botonCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCinco.setFocusPainted(false);

        botonNueve.setBackground(new java.awt.Color(255, 255, 255));
        botonNueve.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonNueve.setForeground(new java.awt.Color(5, 29, 59));
        botonNueve.setText("9");
        botonNueve.setBorder(null);
        botonNueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonNueve.setFocusPainted(false);

        botonTres.setBackground(new java.awt.Color(255, 255, 255));
        botonTres.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonTres.setForeground(new java.awt.Color(5, 29, 59));
        botonTres.setText("3");
        botonTres.setBorder(null);
        botonTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTres.setFocusPainted(false);

        botonPunto.setBackground(new java.awt.Color(255, 255, 255));
        botonPunto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonPunto.setForeground(new java.awt.Color(5, 29, 59));
        botonPunto.setText(".");
        botonPunto.setBorder(null);
        botonPunto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPunto.setFocusPainted(false);

        botonSeis.setBackground(new java.awt.Color(255, 255, 255));
        botonSeis.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonSeis.setForeground(new java.awt.Color(5, 29, 59));
        botonSeis.setText("6");
        botonSeis.setBorder(null);
        botonSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSeis.setFocusPainted(false);

        botonPor.setBackground(new java.awt.Color(255, 255, 255));
        botonPor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonPor.setForeground(new java.awt.Color(5, 29, 59));
        botonPor.setText("x");
        botonPor.setBorder(null);
        botonPor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPor.setFocusPainted(false);

        botonEntre.setBackground(new java.awt.Color(255, 255, 255));
        botonEntre.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonEntre.setForeground(new java.awt.Color(5, 29, 59));
        botonEntre.setText("÷");
        botonEntre.setBorder(null);
        botonEntre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEntre.setFocusPainted(false);

        botonMas.setBackground(new java.awt.Color(255, 255, 255));
        botonMas.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonMas.setForeground(new java.awt.Color(5, 29, 59));
        botonMas.setText("+");
        botonMas.setBorder(null);
        botonMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMas.setFocusPainted(false);

        botonIgual.setBackground(new java.awt.Color(163, 255, 191));
        botonIgual.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonIgual.setForeground(new java.awt.Color(5, 29, 59));
        botonIgual.setText("=");
        botonIgual.setBorder(null);
        botonIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIgual.setFocusPainted(false);

        botonMenos.setBackground(new java.awt.Color(255, 255, 255));
        botonMenos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botonMenos.setForeground(new java.awt.Color(5, 29, 59));
        botonMenos.setText("-");
        botonMenos.setBorder(null);
        botonMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenos.setFocusPainted(false);

        textPantallaCalculadora.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textPantallaCalculadora.setForeground(new java.awt.Color(5, 29, 59));
        textPantallaCalculadora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        botonVolver.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(22, 123, 247));
        botonVolver.setText("< Volver");
        botonVolver.setBorder(null);
        botonVolver.setBorderPainted(false);
        botonVolver.setContentAreaFilled(false);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(botonVolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textPantallaCalculadora)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(botonOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonDosCeros, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(botonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(botonSeis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(botonTres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(botonPunto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonMas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonPor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(botonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(textPantallaCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonPor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonDosCeros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadoraBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadoraBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadoraBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadoraBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCalculadoraBasica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCero;
    public javax.swing.JButton botonCinco;
    public javax.swing.JButton botonClear;
    public javax.swing.JButton botonCuatro;
    public javax.swing.JButton botonDos;
    public javax.swing.JButton botonDosCeros;
    public javax.swing.JButton botonEntre;
    public javax.swing.JButton botonIgual;
    public javax.swing.JButton botonMas;
    public javax.swing.JButton botonMenos;
    public javax.swing.JButton botonNueve;
    public javax.swing.JButton botonOcho;
    public javax.swing.JButton botonPor;
    public javax.swing.JButton botonPunto;
    public javax.swing.JButton botonSeis;
    public javax.swing.JButton botonSiete;
    public javax.swing.JButton botonTres;
    public javax.swing.JButton botonUno;
    public javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField textPantallaCalculadora;
    // End of variables declaration//GEN-END:variables


}
